version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/health-insurance-app
    docker:
      - image: cimg/node:14.17.0 
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest' 
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache- 
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test
