version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build

jobs:
  build:
    working_directory: ~/health-insurance-app-master
    docker:
      - image: cimg/node:18.17.0 
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Mocha Executable
          command: chmod +x ./node_modules/.bin/mocha
  deploy:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-249-234-233.eu-west-1.compute.amazonaws.com "rm -rf health-insurance-app-master/; git clone https://github.com/RyanLanzNCI/health-insurance-app.git health-insurance-app-master; source health-insurance-app-master/deploy.sh"
